name: tac
description: A simple blockchain
# version: 0.1.0
# homepage: https://github.com/lucas979797/tac

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  crypto_hash:
    git:
      url: https://github.com/lucas979797/dart-crypto-hash
      ref: main

dev_dependencies:
  pedantic: ^1.9.0
